name: CI/CD Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install poetry flake8 pytest coverage
          poetry install

      - name: Run linter
        run: make lint

      - name: Run tests with coverage
        run: make test-coverage

      - name: Debug coverage
        run: |
          echo "Checking for coverage.xml"
          ls -la
          cat coverage.xml

      - name: Upload coverage to Code Climate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
            CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
            coverageCommand: make test-coverage
            debug: true
